%YAML:1.0
---
K1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 3.1946522796856794e+02, 0., 1.5822360596271145e+02, 0.,
       3.2052645796617009e+02, 1.2932444007759642e+02, 0., 0., 1. ]
K2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 3.2239855642588617e+02, 0., 1.6178199326458696e+02, 0.,
       3.2334496063931402e+02, 1.2171970040465305e+02, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -4.3109073201095882e-01, 2.0343559746124459e-01,
       1.3666753419088876e-03, 2.6405253679009947e-03,
       4.4459376011390120e-02 ]
D2: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -4.4946218028281093e-01, 3.8045794641613839e-01,
       2.0887436178478267e-04, 7.7425037618123968e-04,
       -3.3363432663802300e-01 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9998584425262171e-01, 1.3818246917057715e-03,
       -5.1382735323060496e-03, -1.3189285715209760e-03,
       9.9992441405872901e-01, 1.2224017209199491e-02,
       5.1547765998761061e-03, -1.2217067153329882e-02,
       9.9991208190939285e-01 ]
T: [ -6.1908978365135613e-02, -5.1942900879655317e-05,
    9.6799670352057680e-04 ]
E: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.0089644594272768e-06, -9.6728894667040847e-04,
       -6.3771142521273290e-05, 1.2871099538026159e-03,
       -7.5500854433449398e-04, 6.1898561614125248e-02,
       1.3359568598852369e-04, -6.1904227140749758e-02,
       -7.5704331377215788e-04 ]
F: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.2030749031668239e-08, -1.1495628857771079e-05,
       1.2418414793252688e-03, 1.5302396096813203e-05,
       -8.9465453374412985e-06, 2.3383326937378410e-01,
       -1.3509762637570095e-03, -2.3423770889214363e-01,
       9.9999999999999989e-01 ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9978158167735243e-01, 2.4115098217549467e-03,
       -2.0759902675857998e-02, -2.2850018493068428e-03,
       9.9997868993253614e-01, 6.1154269971558026e-03,
       2.0774207693199296e-02, -6.0666548598430408e-03,
       9.9976578656879989e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9987743136411722e-01, 8.3891764459159679e-04,
       -1.5633888380076271e-02, -9.3459699514964129e-04,
       9.9998087444108652e-01, -6.1136961403605566e-03,
       1.5628460485657195e-02, 6.1275581780669570e-03,
       9.9985909219930713e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.2193570930274205e+02, 0., 1.6986946296691895e+02, 0., 0.,
       3.2193570930274205e+02, 1.2806199455261230e+02, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.2193570930274205e+02, 0., 1.6986946296691895e+02,
       -1.9933154041687779e+01, 0., 3.2193570930274205e+02,
       1.2806199455261230e+02, 0., 0., 0., 1., 0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -1.6986946296691895e+02, 0., 1., 0.,
       -1.2806199455261230e+02, 0., 0., 0., 3.2193570930274205e+02, 0.,
       0., 1.6150766137132763e+01, 0. ]
